nome=input("Qual seu nome?:")
idade=input("Qual sua idade?:")
peso=input("Qual seu peso?:")
dia=input("Que dia voce nasceu?:")
mes=input("Em que mes voce nasceu?:")
ano=input("Em qual ano voce nasceu?:")
print("Ola",nome,"tudo bem? So confirmando, voce tem:",idade,"anos ,pesa",peso,"kg,e nasceu no dia",dia,"de",mes,"de",ano,"?")
print("Agora voce pode perguntar qualquer tipo de pergunta relacionada a soma")
n1=input("Primeiro Numero: ")
n2=input("Segundo Numero: ")
soma=int(n1)+int(n2)
print("A soma dos numeros eh",soma,)
